apiVersion: apps/v1
kind: Deployment
metadata:
  name: roommate-app
spec:
  selector:
    matchLabels:
      app: roommate-app
  replicas: 1
  template:
    metadata:
      labels:
        app: roommate-app
    spec:
      containers:
        - name: roommate-app
          image: qwerty467/roommate-backend:D-01.001.00-221
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: postgres-secrets

            - secretRef:
                name: minio-secrets

            - secretRef:
                name: bot-secrets

            - secretRef:
                name: sender-secrets

            - secretRef:
                name: jwt-secrets

---

kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  name: roommate-service
  labels:
    name: roommate-app
spec:
  ports:
    - name: roommate-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: roommate-app