{
 "title": "Spring Boot Observability",
 "description": "Observe Spring Boot application with three pillars of observability: Traces (Tempo), Metrics (Prometheus), Logs (Loki) on Grafana through OpenTelemetry and OpenMetrics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "roommate-app", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Статус сервиса",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "up{service=\"roommate-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Общее количество запросов за все время",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_total{service=\"roommate-service\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Длительность выполнения запросов за последние 2 минуты (в секундах)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(request_duration_summary{service=\"roommate-service\"}[2m]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Количество запросов за последние 2 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(requests_total{service=\"roommate-service\"}[2m]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Логи (открывать через explore)",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"roommate-app\"}"
    }
   ]
  }
 ]
}