apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-chown-0
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: grafana-chown
          command: ["/bin/chmod","-R","777", "/data"]
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: loki-prometheus-server