apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-pg
  labels:
    app: storage
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /hosthome/kubernetes/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube #457344.cloud4box.ru #TODO WORKER NODE