apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-minio
  labels:
    app: minio-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  local:
    path: /hosthome/kubernetes/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube #457344.cloud4box.ru #TODO WORKER NODE MINIO