kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
  labels:
    app: minio-storage
spec:
  storageClassName: minio-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi